version: '3'
services:
  app:
    container_name: chat-server
    restart: always
    build: .
    ports:
      - '81:8001'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'